openapi: "3.0.1"
info:
  version: 1.0.0
  title: Swarm Control Center API
  license:
    name: commercial license
  contact:
    name: Michael Rogger
    email: michael.rogger@swarm-analytics.com
    url: https://swarm-analytics.com
servers:
  - url: http://cc.swarm.example.com/v1

paths:

components:
  schemas:
